# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 697)
        self.screen_or = QtWidgets.QLabel(Form)
        self.screen_or.setGeometry(QtCore.QRect(140, 100, 250, 250))
        self.screen_or.setStyleSheet("background-color: rgb(38, 162, 105);")
        self.screen_or.setObjectName("screen_or")
        self.screen_re = QtWidgets.QLabel(Form)
        self.screen_re.setGeometry(QtCore.QRect(560, 100, 250, 250))
        self.screen_re.setStyleSheet("background-color: rgb(38, 162, 105);")
        self.screen_re.setObjectName("screen_re")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(410, 230, 121, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.load_button = QtWidgets.QToolButton(Form)
        self.load_button.setGeometry(QtCore.QRect(420, 520, 121, 31))
        self.load_button.setObjectName("load_button")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(906, 100, 342, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.re = QtWidgets.QLabel(self.gridLayoutWidget)
        self.re.setText("")
        self.re.setObjectName("re")
        self.gridLayout.addWidget(self.re, 3, 1, 1, 1)
        self.time = QtWidgets.QLabel(self.gridLayoutWidget)
        self.time.setText("")
        self.time.setObjectName("time")
        self.gridLayout.addWidget(self.time, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.confidence = QtWidgets.QLabel(self.gridLayoutWidget)
        self.confidence.setText("")
        self.confidence.setObjectName("confidence")
        self.gridLayout.addWidget(self.confidence, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.predict = QtWidgets.QLabel(self.gridLayoutWidget)
        self.predict.setText("")
        self.predict.setObjectName("predict")
        self.gridLayout.addWidget(self.predict, 0, 1, 1, 1)
        self.back_button = QtWidgets.QPushButton(Form)
        self.back_button.setGeometry(QtCore.QRect(360, 440, 89, 25))
        self.back_button.setObjectName("back_button")
        self.next_button = QtWidgets.QPushButton(Form)
        self.next_button.setGeometry(QtCore.QRect(500, 440, 89, 25))
        self.next_button.setObjectName("next_button")
        self.svm_checker = QtWidgets.QRadioButton(Form)
        self.svm_checker.setGeometry(QtCore.QRect(1040, 60, 112, 23))
        self.svm_checker.setChecked(True)
        self.svm_checker.setObjectName("svm_checker")
        self.ann_checker = QtWidgets.QRadioButton(Form)
        self.ann_checker.setGeometry(QtCore.QRect(1160, 60, 112, 23))
        self.ann_checker.setObjectName("ann_checker")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(930, 60, 67, 17))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.screen_or.setText(_translate("Form", "Input Image"))
        self.screen_re.setText(_translate("Form", "Recontructed image"))
        self.load_button.setText(_translate("Form", "Load Image"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#204a87;\">Prediction</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#204a87;\">Inference time</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#204a87;\">Confidence</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#204a87;\">Reconstruction Error</span></p></body></html>"))
        self.back_button.setText(_translate("Form", "<"))
        self.next_button.setText(_translate("Form", ">"))
        self.svm_checker.setText(_translate("Form", "SVM"))
        self.ann_checker.setText(_translate("Form", "ANN"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; text-decoration: underline;\">Classifier</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
